# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# Repo Action 페이지에 나타날 이름 
name: Spring Boot & Gradle CI/CD

# Event Trigger
# master branch에 push 또는 pull request가 발생할 경우 동작
# branch 단위 외에도, tag나 cron 식 등을 사용할 수 있음

on:
  push:
    branches: [ master ]
    paths:
        - "back-end/**"
        - ".github/workflows/back-CI.yml"

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-22.04
    # Task의 sequence를 명시한다.
    # ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
        ## create application.yaml
#      - name: make application.yml
#        working-directory: ./back-end
#        run: |
          ## create application.yml
#          cd ./src/main/resources
          # application.yml 파일 생성
#          touch ./application.yml
          # GitHub-Actions 에서 설정한 값을 application.yaml 파일에 쓰기
#          echo "${{ secrets.DATABASE }}" >> ./application.yml
#        shell: bash

      - name: Grant execute permission for gradlew
        working-directory: ./back-end
        run: chmod +x gradlew
      
      # Build
      - name: Build with Gradle
        working-directory: ./back-end
        run: ./gradlew clean build

      ## 웹 이미지 빌드 및 도커허브에 push
      - name: web docker build and push
        working-directory: ./back-end
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/back-end .
          docker push ${{ secrets.DOCKER_REPO }}/back-end 
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ID }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase : ${{ secrets.PASSPHRASE }}
          port : ${{ secrets.PORT }}
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/back-end
            cd ./docker/back-docker
            docker-compose up -d
            docker image prune -f
