name: Front CI

on:
  push:
    branches: [ "master" ]
    paths:
    #    - "front-end/**"
        - ".github/workflows/front-CI.yml"

jobs: 
  build:
    # 실행 환경 지정
    runs-on: ubuntu-22.04
    # Task의 sequence를 명시한다.
    # ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Check Node v            # Node v 확인
        run: node -v
      
      - name: Generate build          # React Build
        working-directory: ./front-end
        run: npm install
             npm run build
      
      - name: Docker build
        working-directory: ./front-end
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/front-end .
          docker push ${{ secrets.DOCKER_REPO }}/front-end

          
#            sudo docker rm -f $(docker ps -qa)
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ID }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase : ${{ secrets.PASSPHRASE }}
          port : ${{ secrets.PORT }}
          script: | 
            sudo docker stop front-end
            sudo docker rm front-end
            sudo docker pull ${{ secrets.DOCKER_REPO }}/front-end
            cd ./docker/front-docker
            docker-compose up -d
            docker image prune -f
